language: python
python:
    - "3.6"
    - "3.5"
install:
    - pip install coveralls pytest pytest-cov
    - pip install -e .
    - python setup.py install
script:
    - py.test --cov=AdjSim

after_success:
    - coveralls