language: python
python:
    - "3.6"
    - "3.5"
install:
    - pip install coveralls pytest pytest-cov
    - pip install -e .
    - python setup.py install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
    - py.test --cov=AdjSim

after_success:
    - coveralls