package:
  name: adjsim
  version: "2.0.0"

source:
  git_rev: v0.13.1
  git_url: https://github.com/SeverTopan/AdjSim.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - adjsim

about:
  home: https://github.com/SeverTopan/AdjSim
  license: GPL-3.0
  license_file: LICENSE